spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;CASE_INSENSITIVE_IDENTIFIERS=FALSE



